
project_id = "cautkcuzwiwfvixzsuyh"

[functions.fraud-ai]
verify_jwt = true

[functions.ai-learning]
verify_jwt = true

[functions.security-monitor]
verify_jwt = true

[functions.apertus-ai]
verify_jwt = true
