// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cautkcuzwiwfvixzsuyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdXRrY3V6d2l3ZnZpeHpzdXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjc3MjIsImV4cCI6MjA2MjcwMzcyMn0.Cn4by8yZMQTd1BoouW4rd-XJlg_WhDLJLSDsl0vNX2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);